# Generated by Django 3.2 on 2023-05-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title_Genre',
            new_name='TitleGenre',
        ),
    ]
